services:
  db:
    image: postgres:15
    container_name: local-postgres
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi:
    image: trading-sandbox-data-acq:latest   # or whatever tag you gave
    container_name: data_acq
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
